### ISSUE TITLE
Update to WoTLK Classic

### ISSUE THREAD

**Issue by Iowerth** [Benik/LocationPlus#1]
Hello. Seems addon is not updated to WoTLK Classic. Can you please tell will LocationPlus be updated. Now these features are missing:
• Levels range for current zone
• Continent
• Area fishing level
• Professions
• Recommended zones
• Recommended dungeons
• etc

**Comment by Benik** [comment]
Added Professions and Fishing Level in v2.66. All the rest were already there.
