### ISSUE TITLE
Issue on new World Areas (Beta)

### ISSUE THREAD

**Issue by FailZorD** [Benik/LocationPlus#14]
Greetings,

I have attached the LUA Error it gives when trying to load information on the new Areas:

> Message: Interface/AddOns/ElvUI_LocPlus/tooltip.lua:257: attempt to call global 'GetZonePVPInfo' (a nil value)
> Time: Wed Aug 21 19:23:37 2024
> Count: 3
> Stack: Interface/AddOns/ElvUI_LocPlus/tooltip.lua:257: attempt to call global 'GetZonePVPInfo' (a nil value)
> [string "@Interface/AddOns/ElvUI_LocPlus/tooltip.lua"]:257: in function 'GetStatus'
> [string "@Interface/AddOns/ElvUI_LocPlus/tooltip.lua"]:393: in function 'UpdateTooltip'
> [string "@Interface/AddOns/ElvUI_LocPlus/core.lua"]:50: in function <Interface/AddOns/ElvUI_LocPlus/core.lua:41>
> 
> Locals: self = <table> {
>  defaultModuleState = true
>  enabledState = true
>  Title = "LocationPlus "
>  defaultModuleLibraries = <table> {
>  }
>  Config = <table> {
>  }
>  version = "2.87"
>  orderedModules = <table> {
>  }
>  baseName = "ElvUI_LocPlus"
>  modules = <table> {
>  }
>  name = "ElvUI_LocationPlus"
>  moduleName = "LocationPlus"
> }
> color = false
> status = ""
> statusText = nil
> r = 1
> g = 1
> b = 0
> (*temporary) = nil
> (*temporary) = "attempt to call global 'GetZonePVPInfo' (a nil value)"
>

**Comment by Benik** [comment]
Please try with the latest dev version https://github.com/Benik/LocationPlus/archive/refs/heads/development.zip

Ευχαριστώ :)
