### ISSUE TITLE
[WoTLK] Tooltip not working since 2.66

### ISSUE THREAD

**Issue by Iowerth** [Benik/LocationPlus#2]
Hi. Since update to 2.66 tooltip (when hovering mouse on location name) not working.
Other works fine. Tooltip is enabled, of course.

**Comment by Benik** [comment]
Which game version?

**Comment by Benik** [comment]
oops, you said WotLK at the title :D

**Comment by Benik** [comment]
Should be fixed at the dev version. Had to do with fishing level at the player area. Probs on DK starting area.
Will release the fixed version tomorrow.

Thanks for pointing that out :)

**Comment by Iowerth** [comment]
> Should be fixed at the dev version. Had to do with fishing level at the player area. Probs on DK starting area. Will release the fixed version tomorrow.
> 
> Thanks for pointing that out :)

Till fix not released, where can I download the dev version?

**Comment by Benik** [comment]
v2,68 is up. Soz for the delay :P
