### ISSUE TITLE
[WoTLK] Continent and level range

### ISSUE THREAD

**Issue by Iowerth** [Benik/LocationPlus#3]
Hi. Version 2.68 WoTLK.
Maybe I bored you, but i have one more issue. There are:
• no continent names (I'm playing not in English, maybe this is a reason, but in Vanilla it was normal)
• no level range for zones

**Comment by Benik** [comment]
Both Level Range and Continent work fine
![image](https://user-images.githubusercontent.com/1357633/197739296-46200e6b-c19b-4da4-8700-8c55a46c66c7.png)

**Comment by Iowerth** [comment]
Here's the thing, understand. I'll check LibTourist. Thank you!

**Comment by Benik** [comment]
LibTourist is included in Location Plus, you don't have to install it separately. I'm constantly watching if there's a new version.

**Comment by Iowerth** [comment]
> LibTourist is included in Location Plus, you don't have to install it separately. I'm constantly watching if there's a new version.

Your addon has the same version, I checked.

**Comment by Iowerth** [comment]
> The only issue I can think of is if there's another addon that includes an outdated LibTourist version and that addon loads before LocationPlus

Ok, I'll check my Addons folder, thanks.

**Comment by Iowerth** [comment]
> The only issue I can think of is if there's another addon that includes an outdated LibTourist version and that addon loads before LocationPlus

From all my addons only FishingBuddy has lib called LibTouristClassic-1.0. But this addon is disabled on toon where I checked your addon.

**Comment by Benik** [comment]
Which language you are on? The error has to do with localized names in LibTourist

**Comment by Iowerth** [comment]
> Which language you are on? The error has to do with localized names in LibTourist

Russian

**Comment by Benik** [comment]
My guess is that you probably have to create a ticket in LibTourist Classic (WotLK).
https://www.curseforge.com/wow/addons/libtourist-classic/issues

I will leave this ticket open for follow up.
Cheers :)

**Comment by Iowerth** [comment]
You may close this issue because a new version of LibTouristClassic-1.0 and now all is fine ;)
