### ISSUE TITLE
2.68 doesn't show up at all on Retail.

### ISSUE THREAD

**Issue by SJPadbury** [Benik/LocationPlus#4]
2.68 isn't visible at all on Retail. I pulled 2.69 from here, and it seems to be working without any issues that I've seen. Might consider packaging it for the TukUI client?

**Comment by swerenfl** [comment]
Still dont see it even after loading 2.69. Maybe I have a dependency addon turned off?

![image](https://user-images.githubusercontent.com/2687557/198857227-b63241d4-1d1f-4911-a915-7a777e126e6f.png)

**Comment by haazill** [comment]
Hello, so i have same issue, but i see the outline when benkui is on (i see the benkui style i think.)

**Comment by Benik** [comment]
Ooops I forgot to push it on tukui :P

**Comment by Benik** [comment]
v2.70 should be up on Tukui and Curse
