### ISSUE TITLE
Feature: Dragonbane / Community feast

### ISSUE THREAD

**Issue by acesyde** [Benik/LocationPlus#8]
Hi @Benik 

Is it possible to add Dragonbane siege and Community feast timer to the clock tooltip ?

Thk you

**Comment by Benik** [comment]
Hey ace :)
The Time datatext is provided by ElvUI. It's a very good idea, I'll poke ElvUI devs for this

Cheers

**Comment by Benik** [comment]
Unfortunatelly it's gonna be done in ElvUI, at least for now, altough the devs liked the idea. You can use Weak Auras found in wago.io that provide this feature.
