### ISSUE TITLE
Not loading w/ ElvUI 13.25

### ISSUE THREAD

**Issue by dhanrahl** [Benik/LocationPlus#9]
Updated to ElvUI 13.25 today and LocationPlus doesn't seem to load despite being active.

**Comment by MzDykatomy** [comment]
![locplus](https://user-images.githubusercontent.com/118561167/217664581-79939bd4-cc92-48e6-8af4-234f9472535c.jpg)

Maybe this helps

**Comment by dhanrahl** [comment]
Sorry, thought my attachments included.

`38x ...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:505: bad argument #2 to 'max' (number expected, got nil)
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:505: in function `UpdatePanelInfo'
[string "@ElvUI_LocPlus/core.lua"]:493: in function <ElvUI_LocPlus/core.lua:483>
[string "@ElvUI_LocPlus/core.lua"]:556: in function `Initialize'
[string "@ElvUI_LocPlus/core.lua"]:576: in function <ElvUI_LocPlus/core.lua:575>
[string "=[C]"]: ?
[string "@ElvUI/Core/General/Core.lua"]:1810: in function `CallLoadFunc'
[string "@ElvUI/Core/General/Core.lua"]:1823: in function `CallLoadedModule'
[string "@ElvUI/Core/General/Core.lua"]:1851: in function `InitializeModules'
[string "@ElvUI/Core/General/Core.lua"]:1961: in function <ElvUI/Core/General/Core.lua:1930>
[string "=[C]"]: ?
[string "=[C]"]: in function `Initialize'
...
[string "@FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>`

**Comment by Azilroka** [comment]
It is fixed in development

**Comment by dhanrahl** [comment]
Cheers!
